# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fetch_pb2 as fetch__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fetch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PageFetchServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fetch = channel.unary_unary(
                '/grpc.PageFetchService/Fetch',
                request_serializer=fetch__pb2.FetchRequest.SerializeToString,
                response_deserializer=fetch__pb2.FetchResponse.FromString,
                _registered_method=True)
        self.FetchJavDB = channel.unary_unary(
                '/grpc.PageFetchService/FetchJavDB',
                request_serializer=fetch__pb2.FetchRequest.SerializeToString,
                response_deserializer=fetch__pb2.FetchResponse.FromString,
                _registered_method=True)
        self.FetchSehuatang = channel.unary_unary(
                '/grpc.PageFetchService/FetchSehuatang',
                request_serializer=fetch__pb2.FetchRequest.SerializeToString,
                response_deserializer=fetch__pb2.FetchResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/grpc.PageFetchService/Execute',
                request_serializer=fetch__pb2.BrowserJobRequest.SerializeToString,
                response_deserializer=fetch__pb2.BrowserJobResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/grpc.PageFetchService/Health',
                request_serializer=fetch__pb2.BrowserHealthRequest.SerializeToString,
                response_deserializer=fetch__pb2.BrowserHealthResponse.FromString,
                _registered_method=True)


class PageFetchServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Fetch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchJavDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchSehuatang(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PageFetchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=fetch__pb2.FetchRequest.FromString,
                    response_serializer=fetch__pb2.FetchResponse.SerializeToString,
            ),
            'FetchJavDB': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchJavDB,
                    request_deserializer=fetch__pb2.FetchRequest.FromString,
                    response_serializer=fetch__pb2.FetchResponse.SerializeToString,
            ),
            'FetchSehuatang': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchSehuatang,
                    request_deserializer=fetch__pb2.FetchRequest.FromString,
                    response_serializer=fetch__pb2.FetchResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=fetch__pb2.BrowserJobRequest.FromString,
                    response_serializer=fetch__pb2.BrowserJobResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=fetch__pb2.BrowserHealthRequest.FromString,
                    response_serializer=fetch__pb2.BrowserHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.PageFetchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.PageFetchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PageFetchService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.PageFetchService/Fetch',
            fetch__pb2.FetchRequest.SerializeToString,
            fetch__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchJavDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.PageFetchService/FetchJavDB',
            fetch__pb2.FetchRequest.SerializeToString,
            fetch__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchSehuatang(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.PageFetchService/FetchSehuatang',
            fetch__pb2.FetchRequest.SerializeToString,
            fetch__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.PageFetchService/Execute',
            fetch__pb2.BrowserJobRequest.SerializeToString,
            fetch__pb2.BrowserJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.PageFetchService/Health',
            fetch__pb2.BrowserHealthRequest.SerializeToString,
            fetch__pb2.BrowserHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
